### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by JelleHissink** [Taritsyn/DartSassHost#1]
Hi,

I was wondering if you managed to make any progress on this project or if you abandoned work on this?
LibSassHost is used in https://github.com/johan-v-r/LibSassBuilder and if possible I would like to upgrade that project to use dart sass.

Regards,
Jelle Hissink

**Comment by Taritsyn** [comment]
Hello, Jelle!

Work on the SassHost project has been suspended being due to lack of time. When I have free time, then I will return to work on it.

**Comment by JelleHissink** [comment]
Ok, good to know, thanks for the quick response though.

**Comment by Liero** [comment]
Any timeframe when this might be production ready?

**Comment by Taritsyn** [comment]
Hello, Daniel!

I plan to make a preview release until the end of month.

**Comment by Liero** [comment]
Ok. Now that Bootstrap 5 customization requires sass-dart, the release will be highly expected and appreciated. 

See for example this: https://github.com/excubo-ag/WebCompiler/issues/31#issuecomment-821176574
and this: https://github.com/excubo-ag/WebCompiler/issues/18#issuecomment-724711455

Plus there is huge amount of projects using madskristensen's WebCompiler, that has the same problem

**Comment by Brandinga** [comment]
> I plan to make a preview release until the end of month.

Nice!
You are amazing, thank you

**Comment by Taritsyn** [comment]
[Version 1.0.0 Preview 1](https://github.com/Taritsyn/DartSassHost/releases/tag/v1.0.0-preview.1) has been released.

**Comment by JelleHissink** [comment]
Great, I managed to integrate it, a basic test went without any problems!

**Comment by Taritsyn** [comment]
Hello, Jelle!

[First stable release](https://github.com/Taritsyn/DartSassHost/releases/tag/v1.0.0) was released yesterday.

**Comment by JelleHissink** [comment]
:-) Thanks for the update!
