### ISSUE TITLE
Exitcode 139 in Linux

### ISSUE THREAD

**Issue by nojaf** [Taritsyn/DartSassHost#10]
Hello,

I'm using this library to compile some Sass to CSS inside an F# script.
My code looks somewhat like:

```fsharp
#r "nuget: JavaScriptEngineSwitcher.ChakraCore.Native.win-x64"
#r "nuget: JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64"
#r "nuget: JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64"
#r "nuget: JavaScriptEngineSwitcher.ChakraCore, 3.19.0"
#r "nuget: DartSassHost, 1.0.0-preview8"

open System
open System.IO
open DartSassHost
open DartSassHost.Helpers
open JavaScriptEngineSwitcher.ChakraCore
open FSharp.Control.Reactive

let sassCompiler = new SassCompiler (new ChakraCoreJsEngineFactory ())
let (</>) a b = Path.Combine (a, b)
let inputFileToolpage = __SOURCE_DIRECTORY__ </> "online-tool.sass"
let inputFileTemplate = __SOURCE_DIRECTORY__ </> "template.sass"
let inputFolder = __SOURCE_DIRECTORY__
let outputToolPage = __SOURCE_DIRECTORY__ </> ".." </> ".tool" </> "online-tool.css"
let outputTemplate = __SOURCE_DIRECTORY__ </> "../assets/" </> "template.css"

let compileSass () =
    try
        let homepage =
            sassCompiler.CompileFile (inputFileToolpage, ?outputPath = Some outputToolPage)

        let template =
            sassCompiler.CompileFile (inputFileTemplate, ?outputPath = Some outputTemplate)

        File.WriteAllText (outputToolPage, homepage.CompiledContent)
        printfn "Compiled %s at %A" outputToolPage DateTime.Now

        File.WriteAllText (outputTemplate, template.CompiledContent)
        printfn "Compiled %s at %A" outputTemplate DateTime.Now

    with
    | :? SassCompilerLoadException as sclex ->
        printfn
            "During loading of Sass compiler an error occurred. See details:\n%s"
            (SassErrorHelpers.GenerateErrorDetails sclex)
    | :? SassCompilationException as sce ->
        printfn
            "During compilation of SCSS code an error occurred. See details:\n%s"
            (SassErrorHelpers.GenerateErrorDetails sce)
    | :? SassException as e ->
        printfn
            "During working of Sass compiler an unknown error occurred. See details:\n%s"
            (SassErrorHelpers.GenerateErrorDetails e)
    | ex -> printfn "Unexpected exception during Sass compilation: %A" ex

compileSass ()
```

This all works fine but when executing the script on Linux, I always exit with code `139`.
I was able to isolate it to `sassCompiler.CompileFile`.
The moment I remove that line, I get exit code `0`.
In every case, my Sass is compiled to CSS and I can save it to disk.

I'm just a bit annoyed with that exit code in my CI system.
It does not occur on Windows, is there anything I should take into account when running on Linux?

**Comment by Taritsyn** [comment]
Hello, Florian!

ChakraCore library does not always work stably under Linux. I recommend that you try using a [JavaScriptEngineSwitcher.V8](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/V8) module.

**Comment by Taritsyn** [comment]
By the way, what versions of the `JavaScriptEngineSwitcher.ChakraCore.Native.*` packages are you using (it's just not visible from the example)?

**Comment by nojaf** [comment]
Well, I just include all of them in the script and that seems to work cross-platform then.
Updating to `V8` did the trick. Many thanks for pointing this out!

**Comment by Taritsyn** [comment]
>Well, I just include all of them in the script and that seems to work cross-platform then.
>
> #r "nuget: JavaScriptEngineSwitcher.ChakraCore.Native.win-x64"
> #r "nuget: JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64"
> #r "nuget: JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64"

Unlike other packages, there are no version numbers listed here.

It's just that in the latest versions of the JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64 package, some errors that led to the SIGSEGV were fixed.

**Comment by nojaf** [comment]
Ah, yes it will take the latest version on the CI as it wouldn't be in the cache there.
In this case, it would take `3.18.2`.
I'm honestly happy with the `V8` suggestion. 
Thanks again for the pointer, feel free to close this.
