### ISSUE TITLE
SassCompiler messes with tests (and my head)

### ISSUE THREAD

**Issue by stefanloerwald** [Taritsyn/DartSassHost#2]
Hi @Taritsyn,

I'm currently trying to integrate DartSassHost into https://github.com/excubo-ag/WebCompiler/. I have one test failure on **linux** systems, which completely baffles me. I've reduced it now to this tiny case:

-  test.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DartSassHost" Version="1.0.0-preview3" />
    <PackageReference Include="JavaScriptEngineSwitcher.ChakraCore" Version="3.9.1" />
    <PackageReference Include="JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64" Version="3.9.1" />
    <PackageReference Include="JavaScriptEngineSwitcher.ChakraCore.Native.win-x64" Version="3.9.1" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0-release-20210626-04" />
  </ItemGroup>
</Project>
```

- test.cs
```cs
using DartSassHost;
using NUnit.Framework;
using JavaScriptEngineSwitcher.ChakraCore;
using System.IO;

namespace Namespace
{
    public class Class
    {
        [Test]
        public void Method()
        {
            File.WriteAllText("test.scss", "");
            var result = new DartSassHost.SassCompiler(new ChakraCoreJsEngineFactory())
                .CompileFile("test.scss");
            Assert.AreNotEqual("hello", "hello");
        }
    }
}
```

As you can see, this simply compiles an _empty_ scss file (so nothing should go wrong with that, same happens when the file isn't empty). It then continues to check whether "hello" is not equal to "hello", which on Windows systems produces the expected output

```log
Failed Method [70 ms]
Error Message:
   Expected: not equal to "hello"
But was:  "hello"

Stack Trace:
  at Namespace.Class.Method() in /src/test.cs:line 26
```

However, on linux, this happens:

```log
The active test run was aborted. Reason: Test host process crashed

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt() in System.Private.CoreLib.dll:token 0x60056bc+0x0
   at System.IO.BinaryReader.ReadString() in System.Private.CoreLib.dll:token 0x60056b2+0x6
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable() in Microsoft.TestPlatform.CommunicationUtilities.dll:token 0x6000026+0x8
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken) in Microsoft.TestPlatform.CommunicationUtilities.dll:token 0x6000064+0xa0
   --- End of inner exception stack trace ---.
```

Getting things to this stage, I would have thought this has nothing to do with DartSassHost. However, if you remove the compilation step, the behavior is as expected (i.e. test failure, rather than crash).
```cs
using DartSassHost;
using NUnit.Framework;
using JavaScriptEngineSwitcher.ChakraCore;
using System.IO;

namespace Namespace
{
    public class Class
    {
        [Test]
        public void Method()
        {
            File.WriteAllText("test.scss", "");
            //var result = new DartSassHost.SassCompiler(new ChakraCoreJsEngineFactory())
            //    .CompileFile("test.scss");
            Assert.AreNotEqual("hello", "hello");
        }
    }
}
```

Do you have any idea what's going on here?

Best regards,
Stefan

**Comment by stefanloerwald** [comment]
It seems to depend on the linux version used. I can reproduce this weirdness with the following dockerfile:

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal

WORKDIR /src

COPY test.csproj .
RUN dotnet restore test.csproj

COPY test.cs .
RUN dotnet build --no-restore
RUN dotnet test --no-restore
```

**Comment by Taritsyn** [comment]
Hello, Stefan!

Unfortunately, at the moment I do not have the ability to test this error. I will try to do this at the beginning of next week.

If I were you, I would try to do two things:

 1. Run this example under .NET 5, because .NET 6 is still unstable
 1. Replace the JavaScriptEngineSwitcher.ChakraCore  module by the [JavaScriptEngineSwitcher.V8](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/V8) module, because for the last two years there have been problems in work of the ChakraCore library under Linux on latest versions .NET Core.

**Comment by Taritsyn** [comment]
I would also add the `using` statement to source code of this example.

**Comment by stefanloerwald** [comment]
Hi Andrey,

No worries, no need to rush into testing this.

What I've observed so far is:
- occurs on net5.0 too, just doesn't display the exception message, just "Test host process crashed".
- JavaScriptEngineSwitcher.V8 produces a _different_ exception:

```log
  Failed Method [347 ms]
  Error Message:
   DartSassHost.SassCompilerLoadException : During loading of Sass compiler error has occurred. See the original error message: “RangeError: Array buffer allocation failed
   at new M (DartSassHost.Resources.es6-polyfills.min.js:8:10976) -> ….name!=j})){for(y=(M=function(t){return _(this,M),new D(I(t))})[R]=D[R],p=A(D),h=0;p.length>h;)(g=p[…
   at DartSassHost.Resources.es6-polyfills.min.js:8:11073
   at DartSassHost.Resources.es6-polyfills.min.js:8:12556
   at DartSassHost.Resources.es6-polyfills.min.js:8:43928”.
  ----> JavaScriptEngineSwitcher.Core.JsRuntimeException : RangeError: Array buffer allocation failed
   at new M (DartSassHost.Resources.es6-polyfills.min.js:8:10976) -> ….name!=j})){for(y=(M=function(t){return _(this,M),new D(I(t))})[R]=D[R],p=A(D),h=0;p.length>h;)(g=p[…
   at DartSassHost.Resources.es6-polyfills.min.js:8:11073
   at DartSassHost.Resources.es6-polyfills.min.js:8:12556
   at DartSassHost.Resources.es6-polyfills.min.js:8:43928
  ----> Microsoft.ClearScript.ScriptEngineException : RangeError: Array buffer allocation failed
  ----> Microsoft.ClearScript.ScriptEngineException : RangeError: Array buffer allocation failed
  Stack Trace:
     at DartSassHost.SassCompiler.Initialize()
   at DartSassHost.SassCompiler.CompileFile(String inputPath, String outputPath, String sourceMapPath, CompilationOptions options)
   at Namespace.Class.Method() in /src/test.cs:line 14
--JsRuntimeException
   at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerExecute(String code, String documentName)
   at JavaScriptEngineSwitcher.Core.JsEngineBase.ExecuteResource(String resourceName, Assembly assembly)
   at DartSassHost.SassCompiler.Initialize()
--ScriptEngineException
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.ThrowScheduledException()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke(Action`1 action)
   at Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl.InvokeWithLock(Action action)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ScriptInvoke[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.Execute(UniqueDocumentInfo documentInfo, String code, Boolean evaluate)
   at Microsoft.ClearScript.ScriptEngine.Execute(DocumentInfo documentInfo, String code)
   at Microsoft.ClearScript.ScriptEngine.Execute(String documentName, Boolean discard, String code)
   at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerExecute(String code, String documentName)
--ScriptEngineException
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.ThrowScheduledException()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke[T](Func`2 func)
   at Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl.Execute(UniqueDocumentInfo documentInfo, String code, Boolean evaluate)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ExecuteRaw(UniqueDocumentInfo documentInfo, String code, Boolean evaluate)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ExecuteInternal(UniqueDocumentInfo documentInfo, String code, Boolean evaluate)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass103_0.<Execute>b__0()
   at Microsoft.ClearScript.ScriptEngine.ScriptInvokeInternal[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass110_0`1.<ScriptInvoke>b__0()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.InvokeHostAction(IntPtr pAction)
```

**Comment by stefanloerwald** [comment]
> I would also add the `using` statement to source code of this example.

Sorry, which using statement?

**Comment by Taritsyn** [comment]
> RangeError: Array buffer allocation failed

Very similar to a lack of memory. Memory for `ArrayBuffer` in the V8 is [allocated in a special way](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8RuntimeConstraints_MaxArrayBufferAllocation.htm). In addition, an error occurred at the initialization stage of Sass compiler.

Maybe there is not enough memory allocated in the docker?

> Sorry, which using statement?

I meant that you need to dispose resources manually, and not rely on finalization:

```csharp
[Test]
public void Method()
{
    File.WriteAllText("test.scss", "");
    using (var sassCompiler = new DartSassHost.SassCompiler(new ChakraCoreJsEngineFactory()))
    {
        var result = sassCompiler.CompileFile("test.scss");
    }
    Assert.AreNotEqual("hello", "hello");
}
```

**Comment by stefanloerwald** [comment]
> > RangeError: Array buffer allocation failed
> 
> Very similar to a lack of memory. Memory for `ArrayBuffer` in the V8 is [allocated in a special way](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8RuntimeConstraints_MaxArrayBufferAllocation.htm). In addition, an error occurred at the initialization stage of Sass compiler.
> 
> Maybe there is not enough memory allocated in the docker?

This sounds unlikely to me, given my experience with far more involved docker images.

> > Sorry, which using statement?
> 
> I meant that you need to dispose resources manually, and not rely on finalization:
> 
> ```cs
> [Test]
> public void Method()
> {
>     File.WriteAllText("test.scss", "");
>     using (var sassCompiler = new DartSassHost.SassCompiler(new ChakraCoreJsEngineFactory()))
>     {
>         var result = sassCompiler.CompileFile("test.scss");
>     }
>     Assert.AreNotEqual("hello", "hello");
> }
> ```

That's it! Both with ChakraCore and V8, adding the `sassCompiler.Dispose()` (or the using block) resolves the issue. I wonder what the actual problem is though...

**Comment by Taritsyn** [comment]
>  I wonder what the actual problem is though...

Problem is lack of memory. [Node.js version of Dart Sass](https://www.npmjs.com/package/sass) has a very large size (`sass.dart.js` file weighs about 4 megabytes). Therefore, JS engines requires a large amount of memory to execute it. Manual disposing frees up memory almost instantly.

Same applies to the [Autoprefixer Host](https://github.com/Taritsyn/AutoprefixerHost) library. Only there the JS file size is slightly smaller.

**Comment by stefanloerwald** [comment]
I'm not convinced that this is true. I can allocate 1GB within the test and not dispose it without any hiccup:

```cs
using NUnit.Framework;
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace Namespace
{
    public class Class
    {
        [Test]
        public void Method()
        {
            var disposable = new Disposable(); // undisposed
            var proc = Process.GetCurrentProcess();
            Assert.LessOrEqual(1024 * 1024 * 1024, proc.PrivateMemorySize64);
            Assert.AreNotEqual("hello", "hello");
        }
    }
    public class Disposable : IDisposable
    {
        private readonly IntPtr ptr;
        public Disposable()
        {
            ptr = Marshal.AllocHGlobal(1024 * 1024 * 1024);
        }
        
        public void Dispose()
        {
            Marshal.FreeHGlobal(ptr);
        }
    }
}
```

**Comment by Taritsyn** [comment]
Hello, Stefan!

Code from your last example will lead to native memory leak. If you don't believe me, then run a benchmark, which is located in attached file. In my benchmark, I allocate not 1GB, but only 2MB, so that it does not fail during execution. I got the following results:

```
|         Method |     Mean |     Error |  StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated | Allocated native memory | Native memory leak |
|--------------- |---------:|----------:|--------:|------:|------:|------:|----------:|------------------------:|-------------------:|
|    WithDispose | 303.7 ms |  58.86 ms | 3.23 ms |     - |     - |     - |      24 B |             2,097,152 B |                  - |
| WithoutDispose | 307.6 ms | 105.75 ms | 5.80 ms |     - |     - |     - |      24 B |             2,097,152 B |        2,097,152 B |
```

As for running the DartSassHost in conjunction with a JavaScriptEngineSwitcher.ChakraCore module under Linux, there really is an error here. Segmentation fault occurs during call of finalizer of the `ChakraCoreJsEngine` class. Moreover, such an error never occurs on Windows or macOS. It is absolutely certain that this error occurs in the [ChakraCore](https://github.com/chakra-core/ChakraCore) library. Situation is complicated by the fact that Microsoft no longer supports this library, and community has not yet made its own release.

As for the JavaScriptEngineSwitcher.V8 module, there are no problems with it. Most likely, when running a large number of tests, you just ran out of memory. This happened due to the fact that there were many objects in the finalization queue, and memory simply did not have time to be cleared.

[DisposableBenchmark.zip](https://github.com/Taritsyn/DartSassHost/files/6913157/DisposableBenchmark.zip)

**Comment by stefanloerwald** [comment]
Hi Andrey,

> Code from your last example will lead to native memory leak.

Yes, but that's besides the point. You said that the problem of crashing tests was lack of memory. I only doubt that, because I can allocate much more memory (and not even clean it up) without any issue. In fact, I can even also allocate another GB in managed memory and still not run into any memory issue.

> As for running the DartSassHost in conjunction with a JavaScriptEngineSwitcher.ChakraCore module under Linux, there really is an error here. Segmentation fault occurs during call of finalizer of the `ChakraCoreJsEngine` class. Moreover, such an error never occurs on Windows or macOS. It is absolutely certain that this error occurs in the [ChakraCore](https://github.com/chakra-core/ChakraCore) library. Situation is complicated by the fact that Microsoft no longer supports this library, and community has not yet made its own release.

Okay, so the take away here is to ditch ChakraCore. Thanks for making it so trivial to switch between the engines! 🎉
