### ISSUE TITLE
JS Files of Dart Sass.

### ISSUE THREAD

**Issue by AlexisIndustries** [Taritsyn/DartSassHost#3]
Hi!

it is not really an issue, it is just a question and a question is too simple: 

Your project contains compiled files of dart sass. How did you compile dart sass into js file or where do you get this files from?

**Comment by Taritsyn** [comment]
Hello!

I get a `sass.dart.js` file from the [sass](https://www.npmjs.com/package/sass) NPM package.

**Comment by AlexisIndustries** [comment]
But what is that file: `sass-combined.es6`? It has a different structure and why the file with the extension `.es6`?

(Sorry for so dumb questions)

**Comment by Taritsyn** [comment]
The `sass-combined.es6` file contains a Node.js polyfills and modified version of the `sass.dart.js` file, in which all  operations on the file system are replaced with functionality from a .NET file manager (instance of class that implements the [`IFileManager`](https://github.com/Taritsyn/DartSassHost/blob/main/src/DartSassHost/IFileManager.cs) interface). A file with the `.es6` extension is then translated into  ECMAScript 5 by using the Babel.

It took me quite a long time to make all this just workable.

**Comment by AlexisIndustries** [comment]
Okay, thank you for answers! Im just building small ASP.NET Core Application and I want to implement small Sass Middleware so that I want to use `dart sass` for this.

**Comment by AlexisIndustries** [comment]
Okay, thank you for answers! Im just building small ASP.NET Core Application and I want to implement small Sass Middleware so that I want to use `dart sass` for this.
