### ISSUE TITLE
Virtual Filesystem does not work with V8 Engine

### ISSUE THREAD

**Issue by swiftMessenger** [Taritsyn/DartSassHost#8]
In a .Net Framework 4.8 project I added the following 3 NuGet packages:
1) DartSassHost (1.0.0-preview8)
2) JavaScriptEngineSwitcher.V8 (3.20.2)
3) Microsoft.ClearScript.V8.Native.win-x64 (7.3.2)

I configured the Javascript engine switcher in a static function:
```
IJsEngineSwitcher engineSwitcher = JsEngineSwitcher.Current;
var factory = new V8JsEngineFactory();
engineSwitcher.EngineFactories.Add(factory);
engineSwitcher.DefaultEngineName = factory.EngineName;
```

Then I attempted to compile a stylesheet using the following code:
```
var options = new CompilationOptions { SourceMap = false, OutputStyle = OutputStyle.Compressed };
var virtualFileReader = new CustomVirtualFileManager("/");
var compiler = new SassCompiler(virtualFileReader, options);
var initialContent = "@import \"subdirectory/filename.scss\"; ...";
var result = compiler.Compile(initialContent, "/main.scss");
```

Which resulted in an error: `Message: During Compilation of Sass code by using the Sass compiler a JavaScript error has occurred: TypeError: e.GetCurrentDirectory is not a function`

Switching from V8JsEngineFactory to ChakraCoreJsEngineFactory with no other changes caused the stylesheet to compile successfully.

Since I can still use this library with the Chakra Core JS Engine this is not a showstopper issue for me, but I thought that this bug should be documented somewhere so that you have an opportunity to fix it and also to help other people who might encounter the same issue to know that there is a workaround.

**Comment by Taritsyn** [comment]
Hello, Levi!

> Which resulted in an error: Message: `During Compilation of Sass code by using the Sass compiler a JavaScript error has occurred: TypeError: e.GetCurrentDirectory is not a function`
>
> Switching from V8JsEngineFactory to ChakraCoreJsEngineFactory with no other changes caused the stylesheet to compile successfully.

It looks like the `CustomVirtualFileManager` class has a non-public modifier. Some JS engines, including the Microsoft ClearScript.V8, cannot interop with non-public classes, so it is always recommended to make such types public:

```csharp
public sealed class CustomVirtualFileManager : IFileManager
{
    …
}
```

> I configured the Javascript engine switcher in a static function:
>
> IJsEngineSwitcher engineSwitcher = JsEngineSwitcher.Current;
> var factory = new V8JsEngineFactory();
> engineSwitcher.EngineFactories.Add(factory);
> engineSwitcher.DefaultEngineName = factory.EngineName;

This code can be made shorter:

```csharp
JsEngineSwitcher engineSwitcher = JsEngineSwitcher.Current;
engineSwitcher.EngineFactories.AddV8();
engineSwitcher.DefaultEngineName = V8JsEngine.EngineName;
```

It is also possible to abandon the JavaScript Engine Switcher infrastructure and pass an instance of JS engine factory to Sass compiler constructor:

```csharp
var compiler = new SassCompiler(new V8JsEngineFactory(), virtualFileReader, options);
```

Also, don't forget to clean up a Sass compiler resources: create an instance of it in the `using` statement or call the `Dispose` method in the `finally` block.

**Comment by swiftMessenger** [comment]
> It looks like the CustomVirtualFileManager class has a non-public modifier. Some JS engines, including the Microsoft ClearScript.V8, cannot interop with non-public classes, so it is always recommended to make such types public

This was exactly the issue. Thanks!
Interesting that the same code worked with ChakraCore but not V8.
